name: Publish
on:
  push:
    tags:
      - "v*"
jobs:
  build_and_check:
    name: publish
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      GH_TOKEN: ${{ github.token }}
    permissions:
      actions: read
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if latest release
        id: check-latest
        run: |
          CURRENT_TAG="${GITHUB_REF#refs/tags/}"
          echo "Current Tag: ${CURRENT_TAG}"

          LATEST_TAG=$(gh release list --order desc --limit 1 --json tagName -q '.[].tagName')
          echo "Latest Tag: ${LATEST_TAG}"

          HIGHEST_TAG=$(printf '%s\n%s\n' "${CURRENT_TAG}" "${LATEST_TAG}" | sort -V | tail -n1)
          echo "Highest Tag: ${HIGHEST_TAG}"

          if [ "${CURRENT_TAG}" = "${HIGHEST_TAG}" ]; then
            echo "Current tag is the latest."
            echo "::set-output name=result::true"
          else
            echo "Current tag is not the latest."
            echo "::set-output name=result::false"
          fi

      - name: Run when latest
        if: steps.check-latest.outputs.result == 'true'
        run: echo "Run when latest was executed"

      - name: Skip when latest
        if: steps.check-latest.outputs.result != 'true'
        run: echo "Skip when latest was executed"

      - name: Conditional when latest
        run: |
          if [ "${{ steps.check-latest.outputs.result }}" = "true" ]; then
            echo "Conditional when latest IF was executed"
          else
            echo "Conditional when latest ELSE was executed"
          fi

      - name: Always last step
        run: |
          echo "${{ steps.check-latest }}"
          echo "${{ steps.check-latest.outputs }}"
